# .github/workflows/ci.yaml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ewhiteboard
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      # Django 的 DATABASE_URL，如果你在 settings.py 用 dj-database-url 解析
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ewhiteboard

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            sleep 1
          done

      - name: Run migrations
        run: |
          python manage.py migrate --noinput

      - name: Run tests with coverage
        run: |
          coverage run --source='.' manage.py test

      - name: Generate coverage reports
        run: |
          coverage xml -o coverage.xml
          coverage html -d coverage_html

      - name: Upload coverage XML
        uses: actions/upload-artifact@v3
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html
          path: coverage_html
